// This file lives inside the blog package rather than as a standalone package
// because it uses blog-specific import specifiers like #config and #lib, which
// would not resolve in an independent package.
import type { PluginOption } from "vite";
import type { Post } from "#lib/posts.ts";
import * as config from "#config";
import pathutil from "node:path";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { readPosts } from "#lib/posts.server.ts";
import { spawn } from "node:child_process";

const rootDir = pathutil.resolve(import.meta.dirname, "..");
const blogRoutesDir = pathutil.resolve(rootDir, "src/routes/(site)/blog");
const generatedDir = pathutil.resolve(rootDir, "src/lib/generated");
const componentsSpecifierPrefix = "$lib/components";

export default function vitePluginPosts2routes(): PluginOption {
  return {
    name: "vite-plugin-posts2routes",
    config: {
      order: "pre",
      async handler(_config, env): Promise<void> {
        await generate();
        if (env.command === "build") {
          await runSvelteKitSync();
        }
      },
    },
    configureServer(server): void {
      server.watcher.add(config.postsDir);
      const onChange = (filename: string): void => {
        if (!filename.endsWith(".md") || !filename.startsWith(config.postsDir)) {
          return;
        }
        (async (): Promise<void> => {
          await generate();
          server.ws.send({ type: "full-reload" });
        })();
      };
      server.watcher.on("change", onChange);
      server.watcher.on("add", onChange);
      server.watcher.on("unlink", onChange);
    },
  };
}

async function generate(): Promise<void> {
  const posts = await readPosts();
  await rm(blogRoutesDir, { recursive: true, force: true });
  await mkdir(blogRoutesDir, { recursive: true });
  await mkdir(generatedDir, { recursive: true });
  await Promise.all([
    writeFile(pathutil.join(generatedDir, "posts.ts"), postsModule(posts)),
    ...posts.map(async (post) => {
      const dir = pathutil.join(blogRoutesDir, post.slug);
      await mkdir(dir, { recursive: true });
      await writeFile(pathutil.join(dir, "+page.svelte"), postPage(post));
    }),
  ]);
}

function postsModule(posts: readonly Post[]): string {
  const meta = posts.map((post) => ({
    slug: post.slug,
    title: post.title,
    date: post.date,
    description: post.description,
    tags: post.tags,
  }));
  return `// Generated by vite-plugin-posts2routes. Do not edit.
import type { PostMeta } from "$lib/posts.ts";

export const posts: readonly PostMeta[] = ${JSON.stringify(meta, undefined, 2)};
`;
}

function postPage(post: Post): string {
  const imports = ["PostLayout", ...post.svelteComponents]
    .map(
      (name) =>
        `  import ${name} from ${JSON.stringify(`${componentsSpecifierPrefix}/${name}.svelte`)};`,
    )
    .join("\n");
  return `<!-- Generated by vite-plugin-posts2routes. Do not edit. -->
<script lang="ts">
${imports}
</script>

<PostLayout
  title={${JSON.stringify(post.title)}}
  date={${JSON.stringify(post.date)}}
  tags={${JSON.stringify(post.tags)}}
  toc={${JSON.stringify(post.toc)}}
>
${post.markup}
</PostLayout>
`;
}

async function runSvelteKitSync(): Promise<void> {
  const cmd = pathutil.resolve(rootDir, "node_modules/.bin/svelte-kit");
  const child = spawn(cmd, ["sync"], { cwd: rootDir });
  const { resolve, reject, promise } = Promise.withResolvers<void>();
  child.on("error", reject);
  child.on("close", (code) => {
    if (code === 0) {
      resolve();
    } else {
      reject(new Error(`svelte-kit sync exited with code ${String(code)}`));
    }
  });
  await promise;
}
